Merge updates (too many, next time I do better)
Aodarium/Cognitive-affective-map-dashboard pull request #3
Opened 2024-05-14 12:49 UTC by Camel-app

2024-05-14 19:28 UTC, Aodarium requested changes

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.tsx
> +    <footer className={classes.footer}>
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.tsx
> +  { link: 'https://github.com/Camel-app', label: 'by Julius Fenn, Florian Gouret', target: "_blank"},
Link not valid

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.tsx
> +import { IconBrandTwitter, IconBrandYoutube } from '@tabler/icons-react';
Icon not used

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.tsx
> +      className={classes.link}
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.tsx
> +      <Container size="md" className={classes.inner}>
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Footer/Footer.module.css
> +.footer {
See if there is a component to copy past here from mantine

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +  Anchor,
Some imports not used

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +      <Title className={classes.title} ta="center" mt={10} mb={20}>
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +      <Title className={classes.subtitle} ta="center">
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +      <Title className={classes.subtitle} ta="center">
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +      <Title className={classes.subtitle} ta="center" mt={40}>
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +      <Title className={classes.subtitle} ta="center" mt={40}>
className={classes.footer} should be deleted

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +import classes from './Information.module.css';
Not sure if needed here

2024-05-14 19:28 UTC, Aodarium commented on components/Information/Information.tsx
> +import {
Layout of the page not working

2024-05-14 19:28 UTC, Aodarium commented on components/Welcome/Welcome.tsx
> +import { Title, Text, Anchor, List, ThemeIcon, Button, Group, Center } from '@mantine/core';
delete all className ref

Layout not working

2024-05-14 19:28 UTC, Aodarium commented on components/Welcome/Welcome.tsx
> +        <Text color="dimmed" mt="md">
Color is not valid anymore

2024-05-14 19:28 UTC, Aodarium commented on components/Welcome/Welcome.tsx
> +          <a key="Source code" href="https://github.com/Camel-app" target="_blank">
Wrong link

2024-05-15 11:11 UTC, Camel-app commented on components/Information/Information.tsx
> +import classes from './Information.module.css';
I will check this!

2024-05-15 11:12 UTC, Camel-app commented on components/Welcome/Welcome.tsx
> +import { Title, Text, Anchor, List, ThemeIcon, Button, Group, Center } from '@mantine/core';
I reformat it and only included classname for title / subtitles

2024-05-15 11:13 UTC, Camel-app commented on components/Welcome/Welcome.tsx
> +        <Text color="dimmed" mt="md">
instead it is simply "c"?

2024-05-22 09:43 UTC, FennStatistics commented on components/Footer/Footer.tsx
> +  { link: 'https://github.com/Camel-app', label: 'by Julius Fenn, Florian Gouret', target: "_blank"},
Why?

2024-05-24 07:37 UTC, FennStatistics commented on components/Footer/Footer.tsx
> +  { link: 'https://github.com/Camel-app', label: 'by Julius Fenn, Florian Gouret', target: "_blank"},
is removed

2024-05-24 07:37 UTC, FennStatistics commented on components/Footer/Footer.tsx
> +import { IconBrandTwitter, IconBrandYoutube } from '@tabler/icons-react';
is removed

2024-05-24 07:43 UTC, FennStatistics commented on components/Footer/Footer.tsx
> +    <footer className={classes.footer}>
done

2024-06-03 17:05 UTC, closed without merging